name: Release Central CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'release-central/**'
      - '.github/workflows/ci-release-central.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'release-central/**'
      - '.github/workflows/ci-release-central.yml'

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    env:
     MONGODB_URI: ${{ secrets.MONGODB }}
    defaults:
      run:
        working-directory: ./release-central

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: 'release-central/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install

      - name: Run lint
        run: pnpm run lint

      - name: Run tests
        run: pnpm run test

      - name: Run build
        run: pnpm run build
